### ISSUE TITLE
"unmarshalling empty output" when updating masternode set

### ISSUE THREAD

**Issue by etienne-napoleone** [BuildOnViction/tomochain-v1#433] opened 2019-02-02 07:01 UTC
**Version:**
```
Tomo
Version: 1.2.2-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 89
Go Version: go1.10.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
**Problem:**
Node stops without crashing (container still up), but stop syncing/signing, after this error log:
```
INFO [02-02|02:50:37] Imported new chain segment  blocks=1  txs=0   mgas=0.000  elapsed=2.581ms  mgasps=0.000  number=1372495  hash=71c06d…7dd7d1  cache=12.40mB
INFO [02-02|02:50:37] It's time to update new set of masternodes for the next epoch...
ERROR[02-02|02:50:42] Error when update masternodes set. Stopping node err="abi: unmarshalling empty output"
```

**Comment by ngtuna** [comment] 2019-02-11 03:49
This is actually not a bug. I am going to explain how it works then we can discuss what we should do on this.

At the end of each epoch, all masternodes have to update the new set of masternodes for the up next epoch. They do that by calling smart contract to get the latest set. EVM can be overhead at that point (or EVM is too weak to serve the request) thus leads to the empty output.

We can go over this issue by adding an ad-hoc solution to bypass executing evm and reading directly the memory offset which we exactly have done to speed up the chain execution at v1.2.0, but imo we shouldn't do that everywhere. Executing evm to get the list should be the standard way to go. 

Now to solve this issue, I would suggest to leave it to masternode runner responsibility. Definitely stopping node if it can't get the list is correct; we can support ones who run tmn by adding a health-check. To be correct, after few mins of having this error the container will be exited; thus we can do the health-check at that point to restart it. If ones run tomo directly without container package, it's easy to add a cron job.

wdyt ?

**Comment by etienne-napoleone** [comment] 2019-02-11 04:10
@ngtuna Thanks for the explanation!
I agree with you. Actually my main concern is that it happened but the node didn't stop, it was still up but stuck at this point instead of really stopping + exiting. So the orchestrator couldn't fire a new container.
Any way to fix that?

**Comment by ngtuna** [comment] 2019-02-11 08:02
I think we can update Dockerfile entrypoint to make the tomo command run as the root process. Then the container will stop if that process stops. https://github.com/tomochain/tomochain/blob/master/Dockerfile.node#L39

**Comment by etienne-napoleone** [comment] 2019-02-11 08:04
It's already the case https://github.com/tomochain/tomochain/blob/ee026fc5062ffd547360e8aa8ce86a33f96d2fcf/docker/tomochain/entrypoint.sh#L158
Do you think there is a chance that the tomo process just hang instead of exiting?
Or it was just a glitch in the matrix?

**Comment by ngtuna** [comment] 2019-02-11 08:31
> Do you think there is a chance that the tomo process just hang instead of exiting?

No it exits immediately. `os.Exit(1)` has that power.

https://github.com/tomochain/tomochain/blob/master/core/blockchain.go#L1226
https://github.com/tomochain/tomochain/blob/master/log/root.go#L60

**Comment by etienne-napoleone** [comment] 2019-02-11 08:57
Ok, might have been an isolated problem then! Thanks :)

**Comment by etienne-napoleone** [comment] 2019-02-23 14:45
I think there's still a problem with this. It happens sometimes to some nodes quite randomly, even if the machine load is same as usual.

**Comment by ngtuna** [comment] 2019-03-05 07:03
@thanhnguyennguyen  Can you check the EVM execution behavior for smart contract calls to see if we apply any non-standard method at this point ?

**Comment by thanhnguyennguyen** [comment] 2019-04-02 02:28
Our code is good as smart contract query standards for Go language. 
[Ethereum development with Go book](https://github.com/miguelmota/ethereum-development-with-go-book/blob/master/en/smart-contract-read/README.md)
Ethereum developers community sometimes run into this issue but no solution so far.  It may be a weak point of EVM handling poorly concurrent requests

**Comment by ngtuna** [comment] 2019-04-02 06:49
I think now we can close this issue, as docker-compose can handle auto-restart @etienne-napoleone ?

**Closed as completed** 2019-04-02 06:53 UTC
Labels: bug
